#!/usr/bin/env python3
"""
Generate PDF for Iguazu Falls study page.
Creates a print-friendly version and converts to PDF.
"""
import re, os

BASE = "/mnt/e/My_Projects/bztravel-english-study"
HTML_PATH = f"{BASE}/video/iguazu-falls.html"
PDF_PATH = f"{BASE}/pdf/iguazu-falls.pdf"
FONT_DIR = f"{BASE}/fonts"
os.makedirs(f"{BASE}/pdf", exist_ok=True)

with open(HTML_PATH, "r", encoding="utf-8") as f:
    html = f.read()

# Create print-friendly version
# 1. Add @font-face for Chinese font + print CSS
font_face = '''@font-face {
  font-family: 'NotoSansTC';
  src: url('../fonts/NotoSansTC-VF.ttf') format('truetype');
  font-weight: 100 900;
}
body { font-family: 'NotoSansTC', 'Segoe UI', sans-serif; }
'''
insert_pos = html.find("</style>")
if insert_pos > 0:
    html = html[:insert_pos] + font_face + html[insert_pos:]

# 2. Add @media print rules to show all content
print_css = '''
@media print {
  .acc-body { display: block !important; }
  .para-zh { display: block !important; }
  .para-zh-toggle { display: none !important; }
  .acc-icon { display: none !important; }
  .acc-header { cursor: default !important; }
  .acc-header.open { background: #fafafa !important; border-bottom: 1px solid #e2e8f0 !important; }
  .quiz-choice { pointer-events: none !important; cursor: default !important; }
  .quiz-feedback { display: block !important; }
  .collo-answer { display: block !important; }
  .grammar-answer { display: block !important; }
  .pattern-answer { display: block !important; }
  .collo-play, .collo-play-sm, .collo-play-sm, audio { display: none !important; }
  .video-wrap iframe { display: none !important; }
  .section-nav { display: none !important; }
  .quiz-reset { display: none !important; }
  .header { padding: 20px 16px 30px !important; }
  .header::after { height: 0 !important; }
  .video-wrap { margin-top: 0 !important; box-shadow: none !important; }
  .main-wrap { max-width: 100% !important; padding: 0 20px !important; }
  .section { box-shadow: none !important; border: 1px solid #ddd !important; break-inside: avoid; }
  .vocab-item { break-inside: avoid; }
  * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
}
'''

insert_pos = html.find("</style>")
if insert_pos > 0:
    html = html[:insert_pos] + print_css + html[insert_pos:]

# 3. Add PDF download link in footer
pdf_link = f'''  <div class="footer" style="margin-top:4px">
    <a href="../pdf/iguazu-falls.pdf" target="_blank" style="display:inline-block;padding:10px 20px;background:#1e40af;color:#fff;border-radius:10px;text-decoration:none;font-weight:600;font-size:14px">📄 下載講義 PDF</a>
  </div>'''

# Replace existing footer
html = html.replace(
    '<p style="margin-top:4px">Generated by Hermes Agent · 手機友善 · 摺疊式學習</p>',
    '<p style="margin-top:4px">Generated by Hermes Agent · 手機友善 · 摺疊式學習</p>' + pdf_link
)

# Write updated HTML
with open(HTML_PATH, "w", encoding="utf-8") as f:
    f.write(html)

# Generate PDF with WeasyPrint
from weasyprint import HTML
HTML(string=html, base_url=f"{BASE}/video/").write_pdf(PDF_PATH)
pdf_size = os.path.getsize(PDF_PATH)

print(f"✅ PDF generated: {PDF_PATH}")
print(f"   Size: {pdf_size:,} bytes")
print(f"✅ HTML updated with PDF download link")

# Quick check
doc = __import__('fitz').open(PDF_PATH)
print(f"   Pages: {doc.page_count}")
page0 = doc[0]
text = page0.get_text()
has_zh = any('\u4e00' <= c <= '\u9fff' for c in text)
print(f"   Chinese rendered: {'✅' if has_zh else '❌'}")
