#!/usr/bin/env python3
"""
Batch generate PDFs for all BZ Travel video study pages.
Adds print CSS, @font-face, and download link to each HTML page.
"""
import os, re, glob

BASE = "/mnt/e/My_Projects/bztravel-english-study"
FONT_DIR = f"{BASE}/fonts"
PDF_DIR = f"{BASE}/pdf"
os.makedirs(PDF_DIR, exist_ok=True)

# Font CSS
font_css = '''@font-face {
  font-family: 'NotoSansTC';
  src: url('../fonts/NotoSansTC-VF.ttf') format('truetype');
  font-weight: 100 900;
}
body { font-family: 'NotoSansTC', 'Segoe UI', sans-serif; }
'''

# Print CSS
print_css = '''
@media print {
  .acc-body { display: block !important; }
  .para-zh { display: block !important; }
  .para-zh-toggle { display: none !important; }
  .acc-icon { display: none !important; }
  .acc-header { cursor: default !important; }
  .acc-header.open { background: #fafafa !important; }
  .quiz-choice { pointer-events: none !important; cursor: default !important; }
  .quiz-feedback { display: block !important; }
  .collo-answer, .grammar-answer, .pattern-answer { display: block !important; }
  .collo-play, .collo-play-sm, audio, .quiz-reset { display: none !important; }
  .video-wrap iframe, .section-nav { display: none !important; }
  .header { padding: 20px 16px 30px !important; }
  .header::after { height: 0 !important; }
  .video-wrap { margin-top: 0 !important; box-shadow: none !important; }
  .main-wrap { max-width: 100% !important; padding: 0 20px !important; }
  .section { box-shadow: none !important; border: 1px solid #ddd !important; break-inside: avoid; }
  * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
}
'''

# Find all HTML files
html_files = sorted(glob.glob(f"{BASE}/video/*.html"))

from weasyprint import HTML
import concurrent.futures

def process_video(html_path):
    filename = os.path.basename(html_path)
    pdf_name = filename.replace(".html", ".pdf")
    pdf_path = f"{PDF_DIR}/{pdf_name}"
    
    with open(html_path, "r", encoding="utf-8") as f:
        html = f.read()
    
    # Skip if already processed (has our font)
    if "@font-face" in html and f"../pdf/{pdf_name}" in html:
        return (filename, "skipped", 0)
    
    # Add @font-face
    insert_pos = html.find("</style>")
    if insert_pos > 0 and "@font-face" not in html:
        html = html[:insert_pos] + font_css + html[insert_pos:]
    
    # Add print CSS
    insert_pos = html.find("</style>")
    if insert_pos > 0 and "@media print" not in html:
        html = html[:insert_pos] + print_css + html[insert_pos:]
    
    # Add PDF download link in footer
    pdf_link = f'''  <div class="footer" style="margin-top:4px">
    <a href="../pdf/{pdf_name}" target="_blank" style="display:inline-block;padding:10px 20px;background:#1e40af;color:#fff;border-radius:10px;text-decoration:none;font-weight:600;font-size:14px">📄 下載講義 PDF</a>
  </div>'''
    
    if f"../pdf/{pdf_name}" not in html:
        # Replace last footer div
        html = html.replace(
            '<p style="margin-top:4px">Generated by Hermes Agent · 手機友善 · 摺疊式學習</p>',
            '<p style="margin-top:4px">Generated by Hermes Agent · 手機友善 · 摺疊式學習</p>' + pdf_link
        )
    
    # Write updated HTML
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    
    # Generate PDF
    try:
        HTML(string=html, base_url=f"{BASE}/video/").write_pdf(pdf_path)
        size = os.path.getsize(pdf_path)
        return (filename, "pdf_ok", size)
    except Exception as e:
        return (filename, f"error: {str(e)[:60]}", 0)

# Process in parallel
ok = skipped = error = 0
with concurrent.futures.ThreadPoolExecutor(max_workers=3) as ex:
    fs = {ex.submit(process_video, p): p for p in html_files}
    for f in concurrent.futures.as_completed(fs):
        name, status, size = f.result()
        if status == "skipped":
            skipped += 1
            print(f"  ⏭️ {name} (already done)")
        elif status == "pdf_ok":
            ok += 1
            print(f"  ✅ {name} → PDF ({size:,} bytes)")
        else:
            error += 1
            print(f"  ❌ {name}: {status}")

print(f"\n=== SUMMARY ===")
print(f"  ✅ {ok} generated")
print(f"  ⏭️ {skipped} skipped")
print(f"  ❌ {error} errors")
